apiVersion: v2
name: rdm
version: ${project.version}

dependencies:
  # template chart for application spring services
  - name: spring-app-template
    version: 1.1.4
    repository: oci://harbor.i-novus.ru/library/helm/n2o
    alias: springServices
  # template chart for application generic services
  - name: generic-app-template
    version: 1.2.1
    repository: oci://harbor.i-novus.ru/library/helm/n2o
    alias: genericServices
  - name: generic-job-template
    version: 1.1.3
    repository: oci://harbor.i-novus.ru/library/helm/n2o
    alias: jobs
  # optional chart with infrastructure services: db, kafka, zookeeper etc (usually deployed separately)
  - name: rdm-infrastructure
    version: ${project.version}
    condition: global.infrastructure.install
