include:
  - project: ${PIPELINE_REPOSITORY_PREFIX}devenv/gitlab/pipelines
    file:
      - merge-request.gitlab-ci.yml
      - jira.gitlab-ci.yml

deploy mr stand:
  variables:
    HELM_TIMEOUT: '15m'
    HELM_OPTIONAL_FLAGS: '--wait-for-jobs'

build and verify:
  variables:
    MAVEN_EXTRA_BUILD_OPTIONS: '-Pfrontend-build'
    DC_EXTRA_BUILD_CONFIG: '-f .docker-compose/target/docker-compose.build.mr.yml'

autotesting mr stand:
  extends: .autotesting mr stand
  variables:
    AUTOTEST_MODULE_DIR: './ui-test'
    AUTOTEST_PARAMS: '-Drdm.username=admin -Drdm.password=admin'

# Фейковый job, чтобы работал job jira-updater
# У job jira-updater stage равен .pre или .post (их два, один на .pre, другой на .post)
# В gitlab pipeline почему-то если между .pre и .post нет других job-ов -- pipeline вообще не запускается
# Поэтому, чтобы работал jira-updater, добавляем такой job со stage=test
# Как только появится deploy dev стенда -- данный job можно удалить
fake_job:
  stage:
    - test
  script:
    - echo "This is fake job for jira updater"
  tags:
    - yc-dev-k8s-jira-updater

# Т.к. у нас нет dev-стенда -- убираем post-dev, чтобы в Jira не проставлялась дата установки на develop
post dev:
  rules:
    - when: never
