include:
  - project: ${PIPELINE_REPOSITORY_PREFIX}devenv/gitlab/pipelines
    file:
      - merge-request.gitlab-ci.yml
      - jira.gitlab-ci.yml
      - dev-stand.gitlab-ci.yml

deploy mr stand:
  variables:
    HELM_TIMEOUT: '15m'
    HELM_OPTIONAL_FLAGS: '--wait-for-jobs'

build and verify:
  variables:
    MAVEN_IMAGE_VERSION: 'v4'
    MAVEN_EXTRA_BUILD_OPTIONS: '-X -Djava.io.tmpdir=/tmp -Pfrontend-build'
    DC_EXTRA_BUILD_CONFIG: '-f .docker-compose/target/docker-compose.build.mr.yml'
  before_script:
    - |
      echo "Проверка прав доступа к /tmp"
      ls -ld /tmp
      touch /tmp/file1.ext # Попытка создать файл в /tmp
      if [ -f /tmp/file1.ext ]; then echo "Файл успешно создан"; else echo "Ошибка создания файла"; fi
    - |
      echo "Настройка прав доступа к /tmp"
      chmod 1777 /tmp
      ls -ld /tmp
      touch /tmp/file2.ext # Попытка создать файл в /tmp
      if [ -f /tmp/file2.ext ]; then echo "Файл успешно создан"; else echo "Ошибка создания файла"; fi
    - !reference [".build maven base", "before_script"]

autotesting mr stand:
  extends: .autotesting mr stand
  variables:
    AUTOTEST_MODULE_DIR: './ui-test'
    AUTOTEST_PARAMS: '-Drdm.username=admin -Drdm.password=admin'
  artifacts:
    paths:
      - ./ui-test/build/reports/
    expire_in: 1 week

# Т.к. у нас нет dev-стенда -- убираем post dev, чтобы в Jira не проставлялась дата установки на develop
# Нам из dev-stand.gitlab-ci.yml нужен только build
post dev:
  rules:
    - when: never

# Т.к. у нас нет dev-стенда -- убираем deploy dev stand
deploy dev stand:
  variables:
#    При добавлении dev-стенда нужно разкомментировать, иначе ui будет работать неправильно
#    MAVEN_EXTRA_BUILD_OPTIONS: '-Pfrontend-build'
  rules:
    - when: never
