include:
  - project: ${PIPELINE_REPOSITORY_PREFIX}devenv/gitlab/pipelines
    file:
      - merge-request.gitlab-ci.yml
    ref: NNOC-216

deploy mr stand:
  variables:
    HELM_TIMEOUT: '15m'

build and verify:
  variables:
    MAVEN_EXTRA_BUILD_OPTIONS: '-Pfrontend-build'

autotesting mr stand:
  extends: .autotesting mr stand
  variables:
    AUTOTEST_MODULE_DIR: './ui-test'
    AUTOTEST_PARAMS: '-Drdm.username=admin -Drdm.password=admin'
