language: java
jdk: openjdk14

branches:
  except:
    - master

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
  mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V -Pbuild-all-modules,!l10n

## Build and release to maven central
script:
  mvn --settings .maven.xml clean deploy -Prelease,build-all-modules,!l10n -B -U