version: "3.6"

services:
  backend:
    build:
      context: .
      args:
        JAR_FILE: rdm-service/target/rdm-service.jar

  frontend:
    build:
      context: .
      args:
        JAR_FILE: rdm-frontend/target/rdm.jar

  esnsi:
    build:
      context: .
      args:
        JAR_FILE: rdm-esnsi/target/rdm-esnsi.jar

  db:
    build:
      context: db
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
