version: "3"
services:
  db:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/rdm-database:latest
  backend:
    image: "rdm/backend:${TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm
    depends_on:
      - db
  frontend:
    image: "rdm/frontend:${TAG}"
    depends_on:
      - backend
