version: "3"
services:
  db:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/rdm-database:latest
  backend:
    image: "${PROJECT_NAME}_backend:${TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
    depends_on:
      - db
  frontend:
    image: "${PROJECT_NAME}_frontend:${TAG}"
    depends_on:
      - backend
