version: "3.6"

services:
  backend:
    image: ${DOCKER_REGISTRY}/rdm/backend:${TAG}

  frontend:
    image: ${DOCKER_REGISTRY}/rdm/frontend:${TAG}

  esnsi:
    image: ${DOCKER_REGISTRY}/rdm/esnsi:${TAG}

  db:
    image: ${DOCKER_REGISTRY}/rdm/db:${TAG}
