version: "3.6"

networks:
  default:
    driver: overlay
    attachable: true
#    ipam:
#      config:
#      - subnet: 192.168.1.0/24

services:
  db:
    volumes:
    - rdm-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432"
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
        - node.labels.type == db

  backend:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
    depends_on:
      - db
      - security-admin-backend
    restart: on-failure
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 500M
      placement:
        constraints:
        - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    environment:
      JAVA_OPTS: -Xmx300m
    depends_on:
      - backend
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 700M
      placement:
        constraints:
        - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s

  security-admin-backend:
    environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm
          SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
          SPRING_CLOUD_CONSUL_HOST: ${spring_cloud_consul_host}
          SPRING_DATASOURCE_USERNAME: rdm
          SPRING_DATASOURCE_PASSWORD: rdm
          JAVA_OPTS: -Xmx200m
    depends_on:
      - db
    restart: on-failure
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 500M
      placement:
        constraints:
        - node.labels.dc == hetzner

  security-admin-frontend:
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${spring_cloud_consul_host}
      SPRING_APPLICATION_NAME: "rdm-security-admin-frontend"
      SEC_ADMIN_REST_URL: http://security-admin-backend:8080/api
      JAVA_OPTS: -Xmx300m
    depends_on:
      - security-admin-backend
    ports:
    - "8080"
    deploy:
      resources:
        limits:
          memory: 700M
      placement:
        constraints:
        - node.labels.dc == hetzner

  esnsi-int:
    environment:
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
      JAVA_OPTS: -Xmx200m
      depends_on:
        - db
        - security-admin-backend
      restart: on-failure
      ports:
        - "8080"
      deploy:
        resources:
          limits:
            memory: 500M
        placement:
          constraints:
            - node.labels.dc == hetzner
      healthcheck:
        test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
        interval: 1m
        timeout: 10s
        retries: 3
        start_period: 40s


volumes:
  rdm-db-data:
