version: "3.6"

services:
  backend:
    ports:
      - "8181:8080"

  frontend:
    ports:
      - "8180:8080"

  sync:
    ports:
      - "8183:8080"

  esnsi:
    ports:
      - "8184:8080"

  activemq:
    ports:
      - "8213:61616"
      - "8214:8161"
