version: "3.6"

services:
  backend:
    build:
      context: .
      args:
        JAR_FILE: rdm-rest/target/rdm-rest.jar

  frontend:
    build:
      context: .
      args:
        JAR_FILE: rdm-n2o/target/rdm.jar
