version: "3"
services:
  db:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/rdm-database:latest
  backend:
    image: "${PROJECT_NAME}_backend:${TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm
      SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
    depends_on:
      - db
    restart: on-failure
  frontend:
    image: "${PROJECT_NAME}_frontend:${TAG}"
    depends_on:
      - backend
  security-admin-backend:
    image: "security-admin_backend:latest"
    environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rdm
          SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
          SPRING_CLOUD_CONSUL_HOST: ${spring_cloud_consul_host}
          SEC_ADMIN_REST_URL: http://security-admin-backend:8080/api
          SPRING_DATASOURCE_USERNAME: rdm
          SPRING_DATASOURCE_PASSWORD: rdm

    depends_on:
      - db
    restart: on-failure
  security-admin-frontend:
    image: "security-admin_frontend:latest"
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${spring_cloud_consul_host}
      SPRING_APPLICATION_NAME: "rdm-security-admin-frontend"
      SEC_ADMIN_REST_URL: http://docker.one:8183/api
    depends_on:
      - security-admin-backend


