version: "3.6"

services:
  backend:
    build:
      context: .
      args:
        JAR_FILE: rdm-rest/target/rdm-rest.jar

  frontend:
    build:
      context: .
      args:
        JAR_FILE: rdm-frontend/target/rdm.jar

  esnsi:
    build:
      context: .
      args:
        JAR_FILE: rdm-esnsi/target/rdm-esnsi.jar
