npmRegistryServer: "https://npm.i-novus.ru"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
