server:
  port: ${frontend.default.port}
  servlet:
    context-path: ''
    jsp:
      class-name: org.apache.jasper.servlet.JspServlet
      registered: 'true'
    encoding:
      force: 'true'
      force-response: 'true'

# bootstrap:
spring:
  application:
    name: rdm-frontend
  main:
    allow-bean-definition-overriding: 'true'
  cloud:
    consul:
      config:
        prefix: rdm
        format: yaml
        enabled: ${config.server.enable}
  http:
    encoding:
      force: true
      forceResponse: true
  servlet:
    multipart:
      max-file-size: '-1'
      max-request-size: '-1'
  # i18n
  messages:
    basename: n2o_api_messages,n2o_rest_messages,messages.rdmui ${rdm.l10n.messages}

# Timeout for cxf proxy-client
cxf:
  jaxrs:
    client:
      connection:
        timeout: '1500000'
      receive:
        timeout: '1500000'

# Disable tracing:
# cxf 4.0.5 is incompatible with brave-instrumentation-http 6.0.3
management:
  tracing:
    enabled: false

# RDM
rdm:
  context-path: ''
  backend:
    path: ${backend.default.path}
  # l10n
  l10n:
    support: ${rdm.l10n.support}
  permissions:
    refbook:
      status:
        list: rdm.edit,rdm.archive
    draft:
      version: rdm.edit,rdm.archive
  sso:
    token:
      username: username

# N2O
n2o:
  application:
    id: rdm
  access:
    schema:
      id: rdm
  version:
    copyright:
      text: 2013-2025
  ui:
    min:
      width: 1024px
  api:
    control:
      visibility:
        auto_reset: 'false'
  # N2O loader client
  loader:
    client:
      start: MANUAL
      fail-fast: false
      commands:
        - server: ${access.service.url}/api
          target: systems
          subject: admin
          file: classpath:loaders/systems/systems.json
          auth:
            client-id: ${spring.security.oauth2.client.registration.admin-web.client-id}
            client-secret: ${spring.security.oauth2.client.registration.admin-web.client-secret}
            token-uri: ${access.keycloak.server-url}/realms/${access.keycloak.realm}/protocol/openid-connect/token

        - server: ${access.service.url}/api
          target: permissions
          subject: rdm
          file: classpath:loaders/permissions/rdm.json
          auth:
            client-id: ${spring.security.oauth2.client.registration.admin-web.client-id}
            client-secret: ${spring.security.oauth2.client.registration.admin-web.client-secret}
            token-uri: ${access.keycloak.server-url}/realms/${access.keycloak.realm}/protocol/openid-connect/token

        - server: ${access.service.url}/api
          target: roles
          subject: rdm
          file: classpath:loaders/roles/rdm.json
          auth:
            client-id: ${spring.security.oauth2.client.registration.admin-web.client-id}
            client-secret: ${spring.security.oauth2.client.registration.admin-web.client-secret}
            token-uri: ${access.keycloak.server-url}/realms/${access.keycloak.realm}/protocol/openid-connect/token
